import type { Product } from "./types"
import { ASSET_BASE } from "../../config/assets"

export const atb5oz: Product[] = [
  {
    id: 'atb-5oz-grand-canyon-2010',
    slug: 'atb-5oz-grand-canyon-2010',
    name_en: '5 oz Silver ATB – Grand Canyon',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 14000,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2010/2010_atb_5oz_grand_canyon_ms_a.jpg`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2010/2010_atb_5oz_grand_canyon_ms_b.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-mount-hood-2010',
    slug: 'atb-5oz-mount-hood-2010',
    name_en: '5 oz Silver ATB – Mount Hood',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 13000,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2010/2010_atb_5oz_mount_hood_ms_a.jpg`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2010/2010_atb_5oz_grand_canyon_ms_b.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-yellowstone-2010',
    slug: 'atb-5oz-yellowstone-2010',
    name_en: '5 oz Silver ATB – Yellowstone',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 13400,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2010/2010_atb_5oz_yellowstone_ms_a.jpg`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2010/2010_atb_5oz_grand_canyon_ms_b.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-yosemite-2010',
    slug: 'atb-5oz-yosemite-2010',
    name_en: '5 oz Silver ATB – Yosemite',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 13400,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2010/2010_atb_5oz_yosemite_ms_a.jpg`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2010/2010_atb_5oz_grand_canyon_ms_b.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-hot-springs-2010',
    slug: 'atb-5oz-hot-springs-2010',
    name_en: '5 oz Silver ATB – Hot Springs',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 13200,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2010/2010_atb_hot_springs_ms.jpg`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2010/2010_atb_5oz_grand_canyon_ms_b.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-25oz-complete-2010',
    slug: 'atb-25oz-complete-2010',
    name_en: '25 oz Silver ATB – 2010 Complete Set - Presentation case not included',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 67500,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2010/2010_ATB_Set.jpg`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2010/2010_atb_5oz_grand_canyon_ms_b.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-chickasaw-2011',
    slug: 'atb-5oz-chickasaw-2011',
    name_en: '5 oz Silver ATB – Chickasaw',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 12800,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2011/atb_2011_chickasaw_ms_dmpl_obv_ku1.jpg`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2011/atb_2011_chickasaw_ms_dmpl_rev_ku1.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-gettysburg-2011',
    slug: 'atb-5oz-gettysburg-2011',
    name_en: '5 oz Silver ATB – Gettysburg',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 12700,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2011/atb_2011_gettysburg_ms_dmpl_obv_ku4.jpg`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2011/atb_2011_gettysburg_ms_dmpl_rev_ku4.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-glacier-2011',
    slug: 'atb-5oz-glacier-2011',
    name_en: '5 oz Silver ATB – Glacier',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 12900,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2011/atb_2011_glacier_ms_dmpl_obv_ku3.jpg`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2011/atb_2011_glacier_ms_dmpl_rev_ku3.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-olympic-2011',
    slug: 'atb-5oz-olympic-2011',
    name_en: '5 oz Silver ATB – Olympic',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 12700,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2011/atb_2011_olympic_ms_dmpl_obv_ku2.jpg`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2011/atb_2011_olympic_ms_dmpl_rev_ku2.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-vicksburg-2011',
    slug: 'atb-5oz-vicksburg-2011',
    name_en: '5 oz Silver ATB – Vicksburg',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 12600,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2011/atb_2011_vicksburg_ms_dmpl_obv_ku5.jpg`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2011/atb_2011_vicksburg_ms_dmpl_rev_ku5.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-25oz-complete-2011',
    slug: 'atb-25oz-complete-2011',
    name_en: '25 oz Silver ATB – 2011 Complete Set - Presentation case not included',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 62500,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2011/2011_atb_all.jpg`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2010/2010_atb_5oz_grand_canyon_ms_b.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-acadia-2012',
    slug: 'atb-5oz-acadia-2012',
    name_en: '5 oz Silver ATB – Acadia',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 17250,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2012/2012_atb_acadia_5oz_bu_a.jpg`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2010/2010_atb_5oz_grand_canyon_ms_b.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-denali-2012',
    slug: 'atb-5oz-denali-2012',
    name_en: '5 oz Silver ATB – Denali',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 16500,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2012/2012_atb_denali_bu.jpg`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2010/2010_atb_5oz_grand_canyon_ms_b.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-hawaii-2012',
    slug: 'atb-5oz-hawaii-2012',
    name_en: '5 oz Silver ATB – Hawaii',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 17700,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2012/2012_atb_hawaii_5oz_bu.jpg`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2010/2010_atb_5oz_grand_canyon_ms_b.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-el-chaco-2012',
    slug: 'atb-5oz-el-chaco-2012',
    name_en: '5 oz Silver ATB – El Chaco',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 16900,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2012/atb_2012_el_chaco_culture_ms_dmpl_obv_ky2.jpg`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2012/atb_2012_el_chaco_culture_ms_dmpl_rev_ky2.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-el-yunque-2012',
    slug: 'atb-5oz-el-yunque-2012',
    name_en: '5 oz Silver ATB – El Yunque',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 17200,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2012/atb_2012_el_yunque_ms_dmpl_obv_ky1.jpg`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2012/atb_2012_el_yunque_ms_dmpl_rev_ky1.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-set-2012',
    slug: 'atb-5oz-set-2012',
    name_en: '5 oz Silver ATB – 2012 Complete Set - Presentation case not included',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 83000,
    images: {
      obverse: `${ASSET_BASE}/images/sold/sold_out_trans.png`,
      reverse: `${ASSET_BASE}/images/sold/cosigo_io_infin_trans.png`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-fort-mchenry-2013',
    slug: 'atb-5oz-fort-mchenry-2013',
    name_en: '5 oz Silver ATB – Fort McHenry',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 11500,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2013/atb_2013_fort_mchenry_ms_dmpl_obv_kz0.jpg`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2013/atb_2013_fort_mchenry_ms_dmpl_acw_rev.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-great-basin-2013',
    slug: 'atb-5oz-great-basin-2013',
    name_en: '5 oz Silver ATB – Great Basin',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 11900,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2013/atb_2013_great_basin_ms_dmpl_acz_obv.jpg`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2013/atb_2013_great_basin_ms_dmpl_acz_rev.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-mount-rushmore-2013',
    slug: 'atb-5oz-mount-rushmore-2013',
    name_en: '5 oz Silver ATB – Mount Rushmore',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 12300,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2013/atb_2013_mount_rushmore_ms_dmpl_acv_obv.jpg`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2013/atb_2013_mount_rushmore_ms_dmpl_acv_rev.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-perrys_victory-2013',
    slug: 'atb-5oz-perrys_victory-2013',
    name_en: '5 oz Silver ATB – Perrys Victory',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 11500,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2013/atb_2013_perrys_victory_ms_dmpl_acy_obv.jpg`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2013/atb_2013_perrys_victory_ms_dmpl_acy_rev.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-white-mountain-2013',
    slug: 'atb-5oz-white-mountain-2013',
    name_en: '5 oz Silver ATB – White Mountain',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 12100,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2013/atb_2013_white_mountain_ms_dmpl_acx_obv.jpg`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2013/atb_2013_white_mountain_ms_dmpl_acx_rev.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-set-2013',
    slug: 'atb-5oz-set-2013',
    name_en: '5 oz Silver ATB – Complete Set',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 59000,
    images: {
      obverse: `${ASSET_BASE}/images/sold/sold_out_trans.png`,
      reverse: `${ASSET_BASE}/images/sold/cosigo_io_infin_trans.png`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-arches-2014',
    slug: 'atb-5oz-arches-2014',
    name_en: '5 oz Silver ATB – Arches',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 12700,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2014/atb_2014_arches_ms_dmpl_obv_kz1.jpg`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2014/atb_2014_arches_ms_dmpl_rev_kz1.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-great-sand-dunes-2014',
    slug: 'atb-5oz-great-sand-dunes-2014',
    name_en: '5 oz Silver ATB – Great Sand Dunes',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 13100,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2014/atb_2014_great_sand_dunes_ms_dmpl_obv_kz4.jpg`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2014/atb_2014_great_sand_dunes_ms_dmpl_rev_kz4.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-great-smokey-mountains-2014',
    slug: 'atb-5oz-great-smokey-mountains-2014',
    name_en: '5 oz Silver ATB – Great Smokey Mountains',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 13100,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2014/atb_2014_great_smokey_mountain_ms_dmpl_obv_kz3.jpg`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2014/atb_2014_great_smokey_mountain_ms_dmpl_rev_kz3.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-shenandoah-2014',
    slug: 'atb-5oz-shenandoah-2014',
    name_en: '5 oz Silver ATB – Shenandoah',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 12500,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2014/atb_2014_shenandoah_ms_dmpl_obv_kz2.jpg`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2014/atb_2014_shenandoah_ms_dmpl_rev_kz2.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-everglades-2014',
    slug: 'atb-5oz-everglades-2014',
    name_en: '5 oz Silver ATB – Everglades',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 12100,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2014/2014_US_ATB-5oz_Bul_Everglades.jpg`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2010/2010_atb_5oz_grand_canyon_ms_b.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-set-2014',
    slug: 'atb-5oz-set-2014',
    name_en: '5 oz Silver ATB – Complete Set - Presentation case not included',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 59500,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2014/2014-atbs-all.png`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2010/2010_atb_5oz_grand_canyon_ms_b.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-blue-ridge-2015',
    slug: 'atb-5oz-blue-ridge-2015',
    name_en: '5 oz Silver ATB – Blue Ridge',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 12100,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2015/2015_atb_blue_ridge_5oz_bu.jpg`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2010/2010_atb_5oz_grand_canyon_ms_b.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-bombay-hook-2015',
    slug: 'atb-5oz-bombay-hook-2015',
    name_en: '5 oz Silver ATB – Bombay Hook',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 12700,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2015/2015_atb_bombay_hook_5oz_bu.jpg`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2010/2010_atb_5oz_grand_canyon_ms_b.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-home-stead-2015',
    slug: 'atb-5oz-home-stead-2015',
    name_en: '5 oz Silver ATB – Home Stead',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 12500,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2015/2015_atb_homestead_5oz_bu.jpg`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2010/2010_atb_5oz_grand_canyon_ms_b.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-kisatchie-2015',
    slug: 'atb-5oz-kisatchie-2015',
    name_en: '5 oz Silver ATB – Kisatchie',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 12100,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2015/2015_atb_kisachie_5oz_bu.jpg`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2010/2010_atb_5oz_grand_canyon_ms_b.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-saratoga-2015',
    slug: 'atb-5oz-saratoga-2015',
    name_en: '5 oz Silver ATB – Saratoga',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 12400,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2015/2015_atb_saratoga_5oz_bu_b.jpg`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2010/2010_atb_5oz_grand_canyon_ms_b.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-complete-set-2015',
    slug: 'atb-5oz-complete-set-2015',
    name_en: '5 oz Silver ATB – Complete Set - Presentation case not included',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 59500,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2015/2015_set_a.jpg`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2010/2010_atb_5oz_grand_canyon_ms_b.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-fort-moultrie-2016',
    slug: 'atb-5oz-fort-moultrie-2016',
    name_en: '5 oz Silver ATB – Fort Moultrie',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 12100,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2016/2016_atb_fort_moultrie_5oz_bu.jpg`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2010/2010_atb_5oz_grand_canyon_ms_b.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-harpers-ferry-2016',
    slug: 'atb-5oz-harpers-ferry-2016',
    name_en: '5 oz Silver ATB – Harpers Ferry',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 12200,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2016/2016_atb_harpers_ferry_5oz_bu.jpg`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2010/2010_atb_5oz_grand_canyon_ms_b.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-shawnee-2016',
    slug: 'atb-5oz-shawnee-2016',
    name_en: '5 oz Silver ATB – Shawnee',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 12300,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2016/2016_atb_shawnee_5oz_bu_b.jpg`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2010/2010_atb_5oz_grand_canyon_ms_b.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-theodore-roosevelt-2016',
    slug: 'atb-5oz-theodore-roosevelt-2016',
    name_en: '5 oz Silver ATB – Theodore Roosevelt',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 12700,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2016/2016_atb_theodore_roosevelt_gap_5oz_bu.jpg`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2010/2010_atb_5oz_grand_canyon_ms_b.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-cumberland-gap-2016',
    slug: 'atb-5oz-cumberland-gap-2016',
    name_en: '5 oz Silver ATB – Cumberland Gap',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 12300,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2016/2016_atb_cumberland_gap_5oz_bu.png`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2010/2010_atb_5oz_grand_canyon_ms_b.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-effigy-mounds-2017',
    slug: 'atb-5oz-effigy-mounds-2017',
    name_en: '5 oz Silver ATB – Effigy Mounds',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 11700,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2017/2017_atb_effigy_mounds_iowa_BU_rev.jpg`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2017/2017_atb_effigy_mounds_iowa_BU_obv.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-ellis-island-2017',
    slug: 'atb-5oz-ellis-island-2017',
    name_en: '5 oz Silver ATB – Ellis Island',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 11800,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2017/2017_atb_ellis_island_BU_rev.jpg`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2017/2017_atb_effigy_mounds_iowa_BU_obv.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-fredrick-douglass-2017',
    slug: 'atb-5oz-fredrick-douglass-2017',
    name_en: '5 oz Silver ATB – Fredrick Douglass',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 14700,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2017/2017_atb_frederick_douglass_BU_rev.jpg`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2017/2017_atb_effigy_mounds_iowa_BU_obv.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-george-rodgers-2017',
    slug: 'atb-5oz-george-rodgers-2017',
    name_en: '5 oz Silver ATB – George Rodgers',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 13700,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2017/2017_atb_george_rodgers_BU_rev_a.jpg`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2017/2017_atb_effigy_mounds_iowa_BU_obv.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-ozark-2017',
    slug: 'atb-5oz-ozark-2017',
    name_en: '5 oz Silver ATB – Ozark',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 12100,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2017/2017_atb_ozark_BU_rev.jpg`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2017/2017_atb_effigy_mounds_iowa_BU_obv.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-apostle-islands-2018',
    slug: 'atb-5oz-apostle-islands-2018',
    name_en: '5 oz Silver ATB – Apostle Islands',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 14900,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2018/2018_atb_apostle_islands_5oz_bu.png`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2017/2017_atb_effigy_mounds_iowa_BU_obv.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-block-island-2018',
    slug: 'atb-5oz-block-island-2018',
    name_en: '5 oz Silver ATB – Block Island',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 12900,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2018/2018_atb_block_island_5oz_bu.png`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2017/2017_atb_effigy_mounds_iowa_BU_obv.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-cumberland-island-2018',
    slug: 'atb-5oz-cumberland-island-2018',
    name_en: '5 oz Silver ATB – Cumberland Island',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 13200,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2018/2018_atb_cumberland_island_5oz_bu.png`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2017/2017_atb_effigy_mounds_iowa_BU_obv.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-pictured-rocks-2018',
    slug: 'atb-5oz-pictured-rocks-2018',
    name_en: '5 oz Silver ATB – Pictured Rocks',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 13200,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2018/2018_atb_pictured_rocks_5oz_bu.png`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2017/2017_atb_effigy_mounds_iowa_BU_obv.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-voyageurs-2018',
    slug: 'atb-5oz-voyageurs-2018',
    name_en: '5 oz Silver ATB – Voyageurs',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 14200,
    images: {
      obverse: `${ASSET_BASE}/images/sold/sold_out_trans.png`,
      reverse: `${ASSET_BASE}/images/sold/cosigo_io_infin_trans.png`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-american-memorial-park-2019',
    slug: 'atb-5oz-american-memorial-park-2019',
    name_en: '5 oz Silver ATB – American Memorial Park',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 13800,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2019/2019 5 oz Silver ATB American Memorial Park a.png`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2017/2017_atb_effigy_mounds_iowa_BU_obv.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-lowell-nh-park-2019',
    slug: 'atb-5oz-lowell-nh-park-2019',
    name_en: '5 oz Silver ATB – Lowell NH Park',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 13200,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2019/2019 5 oz Silver ATB Lowell National Historical Park, MA a.png`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2017/2017_atb_effigy_mounds_iowa_BU_obv.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-river-of-no-return-2019',
    slug: 'atb-5oz-river-of-no-return-2019',
    name_en: '5 oz Silver ATB – River Of No Return',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 14200,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2019/2019 5 oz Silver ATB River of no return National Hist. Park, Id a.jpg`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2017/2017_atb_effigy_mounds_iowa_BU_obv.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-san-antonio-2019',
    slug: 'atb-5oz-san-antonio-2019',
    name_en: '5 oz Silver ATB – San Antonio Missions NHP',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 13900,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2019/2019 5 oz Silver ATB San Antonio Missions National Hist. Park, TX a.png`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2017/2017_atb_effigy_mounds_iowa_BU_obv.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-war-in-pacific-nhp-2019',
    slug: 'atb-5oz-war-in-pacific-nhp-2019',
    name_en: '5 oz Silver ATB – War in the Pacific NHP',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 13700,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2019/2019 5 oz Silver ATB War in the Pacific National Hist. Park, GU a.png`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2017/2017_atb_effigy_mounds_iowa_BU_obv.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-set-2019',
    slug: 'atb-5oz-set-2019',
    name_en: '5 oz Silver ATB – 2019 Complete Set - Presentation case not included',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 69500,
    images: {
      obverse: `${ASSET_BASE}/images/atb-5oz/2019/2019_set.jpg`,
      reverse: `${ASSET_BASE}/images/atb-5oz/2017/2017_atb_effigy_mounds_iowa_BU_obv.jpg`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-set-2020',
    slug: 'atb-5oz-set-2020',
    name_en: '5 oz Silver ATB – 2020 Complete Set',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 74500,
    images: {
      obverse: `${ASSET_BASE}/images/sold/sold_out_trans.png`,
      reverse: `${ASSET_BASE}/images/sold/cosigo_io_infin_trans.png`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
  {
    id: 'atb-5oz-set-2021',
    slug: 'atb-5oz-set-2021',
    name_en: '5 oz Silver ATB – 2021 Complete Set',
    name_es: '',
    category: 'atb-5oz',
    price_mxn: 74500,
    images: {
      obverse: `${ASSET_BASE}/images/sold/sold_out_trans.png`,
      reverse: `${ASSET_BASE}/images/sold/cosigo_io_infin_trans.png`,
    },
    metal: 'silver',
    weight_g: 155.5,
    inStock: true,
  },
];

