import type { Product } from './types'
import { ASSET_BASE } from './types'

export const franklinHalf: Product[] = [

    {
    id: 'franklin-1948-d-bu-001',
    slug: 'franklin-1948-d-bu-001',
    name_en: 'Franklin Half Dollar — 1948-D (BU)',
    name_es: 'Dólar Frankiln — 1948-D (BU)',
    category: 'franklin-half',
    price_mxn: 6400,
    images: {
      obverse: `${ASSET_BASE}/images/franklin-half/1948/franklin_1948d_ms_fbl_frosty_key_obv_vdh.jpg`,
      reverse: `${ASSET_BASE}/images/franklin-half/1948/franklin_1948d_ms_fbl_frosty_key_rev_vdh.jpg`,
    },
    metal: 'silver',
    weight_g: 12.5,
    inStock: true,
    },
    {
    id: 'franklin-1948-d-bu-002',
    slug: 'franklin-1948-d-bu-002',
    name_en: 'Franklin Half Dollar — 1948-D (BU)',
    name_es: 'Dólar Frankiln — 1948-D (BU)',
    category: 'franklin-half',
    price_mxn: 7300,
    images: {
      obverse: `${ASSET_BASE}/images/franklin-half/1948/franklin_1948d_ms+_frosty_zzb_obv.jpg`,
      reverse: `${ASSET_BASE}/images/franklin-half/1948/franklin_1948d_ms+_frosty_zzb_rev.jpg`,
    },
    metal: 'silver',
    weight_g: 12.5,
    inStock: true,
    },
    {
    id: 'franklin-1948-d-xf-003',
    slug: 'franklin-1948-d-xf-003',
    name_en: 'Franklin Half Dollar — 1948-D (XF)',
    name_es: 'Dólar Frankiln — 1948-D (XF)',
    category: 'franklin-half',
    price_mxn: 3200,
    images: {
      obverse: `${ASSET_BASE}/images/franklin-half/1948/franklin_1948d_xf_40_perc_bl_patina_key_obv_udz.jpg`,
      reverse: `${ASSET_BASE}/images/franklin-half/1948/franklin_1948d_xf_40_perc_bl_patina_key_rev_udz.jpg`,
    },
    metal: 'silver',
    weight_g: 12.5,
    inStock: true,
    },
    {
    id: 'franklin-1948-p-bu-004',
    slug: 'franklin-1948-p-bu-004',
    name_en: 'Franklin Half Dollar — 1948-P (BU)',
    name_es: 'Dólar Frankiln — 1948-p (BU)',
    category: 'franklin-half',
    price_mxn: 7400,
    images: {
      obverse: `${ASSET_BASE}/images/franklin-half/1948/franklin_1948p_ms_fbl_frosty_key_obv_udh.jpg`,
      reverse: `${ASSET_BASE}/images/franklin-half/1948/franklin_1948p_ms_fbl_frosty_key_rev_udh.jpg`,
    },
    metal: 'silver',
    weight_g: 12.5,
    inStock: true,
    },
    {
    id: 'franklin-1948-p-bu-005',
    slug: 'franklin-1948-p-bu-005',
    name_en: 'Franklin Half Dollar — 1948-P (BU)',
    name_es: 'Dólar Frankiln — 1948-p (BU)',
    category: 'franklin-half',
    price_mxn: 7300,
    images: {
      obverse: `${ASSET_BASE}/images/franklin-half/1948/franklin_1948p_ms_fbl_frosty_key_obv_xdh.jpg`,
      reverse: `${ASSET_BASE}/images/franklin-half/1948/franklin_1948p_ms_fbl_frosty_key_rev_xdh.jpg`,
    },
    metal: 'silver',
    weight_g: 12.5,
    inStock: true,
    },
    {
    id: 'franklin-1949-d-au-006',
    slug: 'franklin-1949-d-au-006',
    name_en: 'Franklin Half Dollar — 1949-D (AU)',
    name_es: 'Dólar Frankiln — 1949-D (au)',
    category: 'franklin-half',
    price_mxn: 6200,
    images: {
      obverse: `${ASSET_BASE}/images/franklin-half/1949/franklin_1949d_au+_patina_xzb_obv.jpg`,
      reverse: `${ASSET_BASE}/images/franklin-half/1949/franklin_1949d_au+_patina_xzb_rev.jpg`,
    },
    metal: 'silver',
    weight_g: 12.5,
    inStock: true,
    },
    {
    id: 'franklin-1949-d-bu-007',
    slug: 'franklin-1949-d-bu-007',
    name_en: 'Franklin Half Dollar — 1949-D (BU)',
    name_es: 'Dólar Frankiln — 1949-D (BU)',
    category: 'franklin-half',
    price_mxn: 7200,
    images: {
      obverse: `${ASSET_BASE}/images/franklin-half/1949/franklin_1949d_ms_fbl_patina_key_obv_udy.jpg`,
      reverse: `${ASSET_BASE}/images/franklin-half/1949/franklin_1949d_ms_fbl_patina_key_rev_udy.jpg`,
    },
    metal: 'silver',
    weight_g: 12.5,
    inStock: true,
    },
    {
    id: 'franklin-1949-d-bu-008',
    slug: 'franklin-1949-d-bu-008',
    name_en: 'Franklin Half Dollar — 1949-D (AU)',
    name_es: 'Dólar Frankiln — 1949-D (AU)',
    category: 'franklin-half',
    price_mxn: 5200,
    images: {
      obverse: `${ASSET_BASE}/images/franklin-half/1949/franklin_1949d_au+_patina_xzb_obv.jpg`,
      reverse: `${ASSET_BASE}/images/franklin-half/1949/franklin_1949d_au+_patina_xzb_rev.jpg`,
    },
    metal: 'silver',
    weight_g: 12.5,
    inStock: true,
    },
    {
    id: 'franklin-1949-p-bu-009',
    slug: 'franklin-1949-p-bu-009',
    name_en: 'Franklin Half Dollar — 1949-P (BU)',
    name_es: 'Dólar Frankiln — 1949-P (BU)',
    category: 'franklin-half',
    price_mxn: 7200,
    images: {
      obverse: `${ASSET_BASE}/images/franklin-half/1949/franklin_1949p_ms_fbl_patina_key_obv_xdi.jpg`,
      reverse: `${ASSET_BASE}/images/franklin-half/1949/franklin_1949p_ms_fbl_patina_key_rev_xdi.jpg`,
    },
    metal: 'silver',
    weight_g: 12.5,
    inStock: true,
    },
]