import type { Product } from './types'
import { ASSET_BASE } from './types'

export const franklinHalf: Product[] = [

    {
    id: 'franklin-1948-d-bu-001',
    slug: 'franklin-1948-d-bu-001',
    name_en: 'Franklin Half Dollar — 1948-D (BU)',
    name_es: 'Dólar Frankiln — 1948-D (BU)',
    category: 'franklin-half',
    price_mxn: 2240,
    images: {
      obverse: `${ASSET_BASE}/images/franklin-half/1948/franklin_1948d_ms_fbl_frosty_key_obv_vdh.jpg`,
      reverse: `${ASSET_BASE}/images/franklin-half/1948/franklin_1948d_ms_fbl_frosty_key_rev_vdh.jpg`,
    },
    metal: 'silver',
    weight_g: 12.5,
    stock: 1,
    inStock: true,
    },
    {
    id: 'franklin-1948-d-bu-002',
    slug: 'franklin-1948-d-bu-002',
    name_en: 'Franklin Half Dollar — 1948-D (BU)',
    name_es: 'Dólar Frankiln — 1948-D (BU)',
    category: 'franklin-half',
    price_mxn: 2530,
    images: {
      obverse: `${ASSET_BASE}/images/franklin-half/1948/franklin_1948d_ms+_frosty_zzb_obv.jpg`,
      reverse: `${ASSET_BASE}/images/franklin-half/1948/franklin_1948d_ms+_frosty_zzb_rev.jpg`,
    },
    metal: 'silver',
    weight_g: 12.5,
    stock: 1,
    inStock: true,
    },
    {
    id: 'franklin-1948-d-xf-003',
    slug: 'franklin-1948-d-xf-003',
    name_en: 'Franklin Half Dollar — 1948-D (XF)',
    name_es: 'Dólar Frankiln — 1948-D (XF)',
    category: 'franklin-half',
    price_mxn: 1880,
    images: {
      obverse: `${ASSET_BASE}/images/franklin-half/1948/franklin_1948d_xf_40_perc_bl_patina_key_obv_udz.jpg`,
      reverse: `${ASSET_BASE}/images/franklin-half/1948/franklin_1948d_xf_40_perc_bl_patina_key_rev_udz.jpg`,
    },
    metal: 'silver',
    weight_g: 12.5,
    stock: 1,
    inStock: true,
    },
    {
    id: 'franklin-1948-p-bu-004',
    slug: 'franklin-1948-p-bu-004',
    name_en: 'Franklin Half Dollar — 1948-P (BU)',
    name_es: 'Dólar Frankiln — 1948-p (BU)',
    category: 'franklin-half',
    price_mxn: 2240,
    images: {
      obverse: `${ASSET_BASE}/images/franklin-half/1948/franklin_1948p_ms_fbl_frosty_key_obv_udh.jpg`,
      reverse: `${ASSET_BASE}/images/franklin-half/1948/franklin_1948p_ms_fbl_frosty_key_rev_udh.jpg`,
    },
    metal: 'silver',
    weight_g: 12.5,
    stock: 1,
    inStock: true,
    },
    {
    id: 'franklin-1948-p-bu-005',
    slug: 'franklin-1948-p-bu-005',
    name_en: 'Franklin Half Dollar — 1948-P (BU)',
    name_es: 'Dólar Frankiln — 1948-p (BU)',
    category: 'franklin-half',
    price_mxn: 2250,
    images: {
      obverse: `${ASSET_BASE}/images/franklin-half/1948/franklin_1948p_ms_fbl_frosty_key_obv_xdh.jpg`,
      reverse: `${ASSET_BASE}/images/franklin-half/1948/franklin_1948p_ms_fbl_frosty_key_rev_xdh.jpg`,
    },
    metal: 'silver',
    weight_g: 12.5,
    stock: 1,
    inStock: true,
    },
    {
    id: 'franklin-1949-d-au-006',
    slug: 'franklin-1949-d-au-006',
    name_en: 'Franklin Half Dollar — 1949-D (AU)',
    name_es: 'Dólar Frankiln — 1949-D (AU)',
    category: 'franklin-half',
    price_mxn: 2050,
    images: {
      obverse: `${ASSET_BASE}/images/franklin-half/1949/franklin_1949d_au+_patina_xzb_obv.jpg`,
      reverse: `${ASSET_BASE}/images/franklin-half/1949/franklin_1949d_au+_patina_xzb_rev.jpg`,
    },
    metal: 'silver',
    weight_g: 12.5,
    stock: 1,
    inStock: true,
    },
    {
    id: 'franklin-1949-d-bu-007',
    slug: 'franklin-1949-d-bu-007',
    name_en: 'Franklin Half Dollar — 1949-D (BU)',
    name_es: 'Dólar Frankiln — 1949-D (BU)',
    category: 'franklin-half',
    price_mxn: 2330,
    images: {
      obverse: `${ASSET_BASE}/images/franklin-half/1949/franklin_1949d_ms_fbl_patina_key_obv_udy.jpg`,
      reverse: `${ASSET_BASE}/images/franklin-half/1949/franklin_1949d_ms_fbl_patina_key_rev_udy.jpg`,
    },
    metal: 'silver',
    weight_g: 12.5,
    stock: 1,
    inStock: true,
    },
    {
    id: 'franklin-1949-d-au-008',
    slug: 'franklin-1949-d-au-008',
    name_en: 'Franklin Half Dollar — 1949-D (AU)',
    name_es: 'Dólar Frankiln — 1949-D (AU)',
    category: 'franklin-half',
    price_mxn: 2250,
    images: {
      obverse: `${ASSET_BASE}/images/franklin-half/1949/franklin_1949d_au+_patina_xzb_obv.jpg`,
      reverse: `${ASSET_BASE}/images/franklin-half/1949/franklin_1949d_au+_patina_xzb_rev.jpg`,
    },
    metal: 'silver',
    weight_g: 12.5,
    stock: 1,
    inStock: true,
    },
    {
    id: 'franklin-1949-p-bu-009',
    slug: 'franklin-1949-p-bu-009',
    name_en: 'Franklin Half Dollar — 1949-P (BU)',
    name_es: 'Dólar Frankiln — 1949-P (BU)',
    category: 'franklin-half',
    price_mxn: 2240,
    images: {
      obverse: `${ASSET_BASE}/images/franklin-half/1949/franklin_1949p_ms_fbl_patina_key_obv_xdi.jpg`,
      reverse: `${ASSET_BASE}/images/franklin-half/1949/franklin_1949p_ms_fbl_patina_key_rev_xdi.jpg`,
    },
    metal: 'silver',
    weight_g: 12.5,
    stock: 1,
    inStock: true,
    },
    {
    id: '2025-2026-15550-cosigo-token',
    slug: '2025-2026-15550-cosigo-token',
    name_en: '15,550 Cosigo Token in your wallet 2026',
    name_es: '15,550 Cosigo Token in your wallet 2026',
    category: 'franklin-half',
    price_mxn: 950,
    images: {
      obverse: `${ASSET_BASE}/images/one-ounce-rounds/cosigo_master_256_obv.png`,
      reverse: `${ASSET_BASE}/images/one-ounce-rounds/cosigo_mark_option_x_256.png`,
    },
    metal: "silver",
    weight_g: 15.550,
    stock: 10,
    inStock: true,
  },
    {
    id: 'franklin-1950-d-xf-010',
    slug: 'franklin-1950-d-xf-010',
    name_en: 'Franklin Half Dollar — 1950-D (XF)',
    name_es: 'Dólar Frankiln — 1950-D (XF)',
    category: 'franklin-half',
    price_mxn: 1540,
    images: {
      obverse: `${ASSET_BASE}/images/franklin-half/1950/franklin_1950d_au_60_perc_bl_patina_semi_key_obv_ueq.jpg`,
      reverse: `${ASSET_BASE}/images/franklin-half/1950/franklin_1950d_au_60_perc_bl_patina_semi_key_rev_ueq.jpg`,
    },
    metal: 'silver',
    weight_g: 12.5,
    stock: 1,
    inStock: true,
    },
    {
    id: 'franklin-1950-d-au-011',
    slug: 'franklin-1950-d-au-011',
    name_en: 'Franklin Half Dollar — 1950-D (AU)',
    name_es: 'Dólar Frankiln — 1950-D (AU)',
    category: 'franklin-half',
    price_mxn: 2040,
    images: {
      obverse: `${ASSET_BASE}/images/franklin-half/1950/franklin_1950d_au_95_perc_bl_patina_semi_key_obv_xey.jpg`,
      reverse: `${ASSET_BASE}/images/franklin-half/1950/franklin_1950d_au_95_perc_bl_patina_semi_key_rev_xey.jpg`,
    },
    metal: 'silver',
    weight_g: 12.5,
    stock: 1,
    inStock: true,
    },
    {
    id: 'franklin-1950-d-bu-012',
    slug: 'franklin-1950-d-bu-012',
    name_en: 'Franklin Half Dollar — 1950-D (BU)',
    name_es: 'Dólar Frankiln — 1950-D (BU)',
    category: 'franklin-half',
    price_mxn: 2440,
    images: {
      obverse: `${ASSET_BASE}/images/franklin-half/1950/franklin_1950d_ms_frosty_yzg_obv.jpg`,
      reverse: `${ASSET_BASE}/images/franklin-half/1950/franklin_1950d_ms_frosty_yzg_rev.jpg`,
    },
    metal: 'silver',
    weight_g: 12.5,
    stock: 1,
    inStock: true,
    },
    {
    id: 'franklin-1950-p-au-013',
    slug: 'franklin-1950-p-au-013',
    name_en: 'Franklin Half Dollar — 1950-P (AU)',
    name_es: 'Dólar Frankiln — 1950-P (AU)',
    category: 'franklin-half',
    price_mxn: 2250,
    images: {
      obverse: `${ASSET_BASE}/images/franklin-half/1950/franklin_1950p_au_90_perc_bl_patina_semi_key_obv_vej.jpg`,
      reverse: `${ASSET_BASE}/images/franklin-half/1950/franklin_1950p_au_90_perc_bl_patina_semi_key_rev_vej.jpg`,
    },
    metal: 'silver',
    weight_g: 12.5,
    stock: 1,
    inStock: true,
    },
    {
    id: 'franklin-1950-p-au-014',
    slug: 'franklin-1950-p-au-014',
    name_en: 'Franklin Half Dollar — 1950-P (AU)',
    name_es: 'Dólar Frankiln — 1950-P (AU)',
    category: 'franklin-half',
    price_mxn: 2750,
    images: {
      obverse: `${ASSET_BASE}/images/franklin-half/1950/franklin_1950p_au+_frosty_yzf_obv.jpg`,
      reverse: `${ASSET_BASE}/images/franklin-half/1950/franklin_1950p_au+_frosty_yzf_rev.jpg`,
    },
    metal: 'silver',
    weight_g: 12.5,
    stock: 1,
    inStock: true,
    },
    {
    id: 'franklin-1950-p-bu-015',
    slug: 'franklin-1950-p-bu-015',
    name_en: 'Franklin Half Dollar — 1950-P (BU)',
    name_es: 'Dólar Frankiln — 1950-P (BU)',
    category: 'franklin-half',
    price_mxn: 3150,
    images: {
      obverse: `${ASSET_BASE}/images/franklin-half/1950/franklin_1950p_ms_fbl_toned_semi_key_obv_xej.jpg`,
      reverse: `${ASSET_BASE}/images/franklin-half/1950/franklin_1950p_ms_fbl_toned_semi_key_rev_xej.jpg`,
    },
    metal: 'silver',
    weight_g: 12.5,
    stock: 1,
    inStock: true,
    },
    {
    id: 'franklin-1950-p-xf-016',
    slug: 'franklin-1950-p-xf-016',
    name_en: 'Franklin Half Dollar — 1950-P (XF)',
    name_es: 'Dólar Frankiln — 1950-P (XF)',
    category: 'franklin-half',
    price_mxn: 1650,
    images: {
      obverse: `${ASSET_BASE}/images/franklin-half/1950/franklin_1950p_xf_patina_xze_obv.jpg`,
      reverse: `${ASSET_BASE}/images/franklin-half/1950/franklin_1950p_xf_patina_xze_rev.jpg`,
    },
    metal: 'silver',
    weight_g: 12.5,
    stock: 1,
    inStock: true,
    },
    {
    id: 'franklin-1951-d-xf-017',
    slug: 'franklin-1951-d-xf-017',
    name_en: 'Franklin Half Dollar — 1951-D (XF)',
    name_es: 'Dólar Frankiln — 1951-D (XF)',
    category: 'franklin-half',
    price_mxn: 2350,
    images: {
      obverse: `${ASSET_BASE}/images/franklin-half/1951/franklin_1951d_au+_patina_xzf_obv.jpg`,
      reverse: `${ASSET_BASE}/images/franklin-half/1951/franklin_1951d_au+_patina_xzf_rev.jpg`,
    },
    metal: 'silver',
    weight_g: 12.5,
    stock: 1,
    inStock: true,
    },
    {
    id: 'franklin-1951-d-bu-018',
    slug: 'franklin-1951-d-bu-018',
    name_en: 'Franklin Half Dollar — 1951-D (BU)',
    name_es: 'Dólar Frankiln — 1951-D (BU)',
    category: 'franklin-half',
    price_mxn: 2750,
    images: {
      obverse: `${ASSET_BASE}/images/franklin-half/1951/franklin_1951d_ms+_frosty_zzi_obv.jpg`,
      reverse: `${ASSET_BASE}/images/franklin-half/1951/franklin_1951d_ms+_frosty_zzi_rev.jpg`,
    },
    metal: 'silver',
    weight_g: 12.5,
    stock: 1,
    inStock: true,
    },
    {
    id: 'franklin-1951-d-au-019',
    slug: 'franklin-1951-d-au-019',
    name_en: 'Franklin Half Dollar — 1951-D (AU)',
    name_es: 'Dólar Frankiln — 1951-D (AU)',
    category: 'franklin-half',
    price_mxn: 2250,
    images: {
      obverse: `${ASSET_BASE}/images/franklin-half/1951/franklin_1951d_xf_60_perc_bl_patina_semi_key_obv_xea.jpg`,
      reverse: `${ASSET_BASE}/images/franklin-half/1951/franklin_1951d_xf_60_perc_bl_patina_semi_key_rev_xea.jpg`,
    },
    metal: 'silver',
    weight_g: 12.5,
    stock: 1,
    inStock: true,
    },
    {
    id: 'franklin-1951-p-au-020',
    slug: 'franklin-1951-p-au-020',
    name_en: 'Franklin Half Dollar — 1951-P (AU)',
    name_es: 'Dólar Frankiln — 1951-P (AU)',
    category: 'franklin-half',
    price_mxn: 2250,
    images: {
      obverse: `${ASSET_BASE}/images/franklin-half/1951/franklin_1951p_au_80_perc_bl_patina_obv_uea.jpg`,
      reverse: `${ASSET_BASE}/images/franklin-half/1951/franklin_1951p_au_80_perc_bl_patina_rev_uea.jpg`,
    },
    metal: 'silver',
    weight_g: 12.5,
    stock: 1,
    inStock: true,
    },
    {
    id: 'franklin-1951-p-bu-021',
    slug: 'franklin-1951-p-bu-021',
    name_en: 'Franklin Half Dollar — 1951-P (BU)',
    name_es: 'Dólar Frankiln — 1951-P (BU)',
    category: 'franklin-half',
    price_mxn: 2750,
    images: {
      obverse: `${ASSET_BASE}/images/franklin-half/1951/franklin_1951p_ms_fbl_patina_obv_xex.jpg`,
      reverse: `${ASSET_BASE}/images/franklin-half/1951/franklin_1951p_ms_fbl_patina_rev_xex.jpg`,
    },
    metal: 'silver',
    weight_g: 12.5,
    stock: 1,
    inStock: true,
    },
    {
    id: 'franklin-1951-p-bu-022',
    slug: 'franklin-1951-p-bu-022',
    name_en: 'Franklin Half Dollar — 1951-P (BU)',
    name_es: 'Dólar Frankiln — 1951-P (BU)',
    category: 'franklin-half',
    price_mxn: 2850,
    images: {
      obverse: `${ASSET_BASE}/images/franklin-half/1951/franklin_1951p_ms_frosty_yzh_obv.jpg`,
      reverse: `${ASSET_BASE}/images/franklin-half/1951/franklin_1951p_ms_frosty_yzh_rev.jpg`,
    },
    metal: 'silver',
    weight_g: 12.5,
    stock: 1,
    inStock: true,
    },
    {
    id: 'franklin-1951-s-bu-023',
    slug: 'franklin-1951-s-bu-023',
    name_en: 'Franklin Half Dollar — 1951-S (BU)',
    name_es: 'Dólar Frankiln — 1951-S (BU)',
    category: 'franklin-half',
    price_mxn: 2450,
    images: {
      obverse: `${ASSET_BASE}/images/franklin-half/1951/franklin_1951s_ms_fbl_patina_obv_vev.jpg`,
      reverse: `${ASSET_BASE}/images/franklin-half/1951/franklin_1951s_ms_fbl_patina_rev_vev.jpg`,
    },
    metal: 'silver',
    weight_g: 12.5,
    stock: 1,
    inStock: true,
    },
    {
    id: 'franklin-1951-s-au-024',
    slug: 'franklin-1951-s-au-024',
    name_en: 'Franklin Half Dollar — 1951-S (AU)',
    name_es: 'Dólar Frankiln — 1951-S (AU)',
    category: 'franklin-half',
    price_mxn: 2250,
    images: {
      obverse: `${ASSET_BASE}/images/franklin-half/1951/franklin_1951s_ms_frosty_yzj_obv.jpg`,
      reverse: `${ASSET_BASE}/images/franklin-half/1951/franklin_1951s_ms_frosty_yzj_rev.jpg`,
    },
    metal: 'silver',
    weight_g: 12.5,
    stock: 1,
    inStock: true,
    },
]