import { Product, ASSET_BASE } from './types'

export const metadata = {
  title: 'Silver Coins One Troy Ounce Rounds BU Proof'
}

export const oneOunceRounds: Product[] = [
  {
    id: '2017-2oz-silver-st-gaudens-BU',
    slug: '2017-2oz-silver-st-gaudens-BU',
    name_en: '2017 2oz silver St Gaudens (BU)',
    name_es: '2017-2oz silver St Gaudens (BU)',
    category: 'one-ounce-rounds',
    price_mxn: 4970,
    images: {
      obverse: `${ASSET_BASE}/images/one-ounce-rounds/2018 Augustus Saint Gaudens 2 oz 39mm 999 Fine Silver High Relief Medal 20 e.jpg`,
      reverse: `${ASSET_BASE}/images/one-ounce-rounds/2018 Augustus Saint Gaudens 2 oz 39mm 999 Fine Silver High Relief Medal 20 f.jpg`,
    },
    metal: "silver",
    weight_g: 62.2070,
    stock: 3,
    inStock: true,
  },
  {
    id: '2012-1oz-silver-wildlife-cananda-cougar-BU',
    slug: '2012-1oz-silver-wildlife-cananda-cougar-BU',
    name_en: '2012 1oz silver wildlife Cananda Cougar (BU)',
    name_es: '2012 1oz silver wildlife Cananda Cougar (BU)',
    category: 'one-ounce-rounds',
    price_mxn: 2790,
    images: {
      obverse: `${ASSET_BASE}/images/one-ounce-rounds/2012-canada-1-oz-silver-wildlife-series-cougar_64598_Slab.jpg`,
      reverse: `${ASSET_BASE}/images/one-ounce-rounds/2012-canada-1-oz-silver-wildlife-series-cougar_64598_Obv.jpg`,
    },
    metal: "silver",
    weight_g: 31.1035,
    stock: 5,
    inStock: true,
  },
  {
    id: '2012-1oz-silver-china-year-of-dragon-BU',
    slug: '2012-1oz-silver-china-year-of-dragon-BU',
    name_en: '2012-1oz-Silver China Year Of Dragon (BU)',
    name_es: '2012-1oz-Silver China Year Of Dragon (BU)',
    category: 'one-ounce-rounds',
    price_mxn: 2480,
    images: {
      obverse: `${ASSET_BASE}/images/one-ounce-rounds/1-oz-silver-round-apmex-2012-year-of-the-dragon_65011_Obv.jpg`,
      reverse: `${ASSET_BASE}/images/one-ounce-rounds/1-oz-silver-round-apmex-2012-year-of-the-dragon_65011_Rev.jpg`,
    },
    metal: "silver",
    weight_g: 31.1035,
    stock: 5,
    inStock: true,
  },
  {
    id: '2025-2026-31000-cosigo-token',
    slug: '2025-2026-31000-cosigo-token',
    name_en: '31,100 Cosigo Token in your wallet 2026',
    name_es: '31,100 Cosigo Token in your wallet 2026',
    category: 'one-ounce-rounds',
    price_mxn: 1800,
    images: {
      obverse: `${ASSET_BASE}/images/one-ounce-rounds/cosigo_master_256_obv.png`,
      reverse: `${ASSET_BASE}/images/one-ounce-rounds/cosigo_mark_option_x_256.png`,
    },
    metal: "silver",
    weight_g: 31.1000,
    stock: 10,
    inStock: true,
  },
  {
    id: '2000-1oz-silver-buffalo-american-indian-BU',
    slug: '2000-1oz-silver-buffalo-american-indian-BU',
    name_en: '2000 1oz Silver Buffalo and American Indian (BU)',
    name_es: '2000 1oz Silver Buffalo and American Indian (BU)',
    category: 'one-ounce-rounds',
    price_mxn: 2480,
    images: {
      obverse: `${ASSET_BASE}/images/one-ounce-rounds/bufalo_indio_ms_obv.jpg`,
      reverse: `${ASSET_BASE}/images/one-ounce-rounds/bufalo_indio_ms_rev.jpg`,
    },
    metal: "silver",
    weight_g: 31.1035,
    stock: 5,
    inStock: true,
  },
  {
    id: '2017-1oz-silver-athenian-owl-BU',
    slug: '2017-1oz-silver-athenian-owl-BU',
    name_en: '2017 1oz Silver Athenian Owl Niue Two Dollars Elizabeth (BU)',
    name_es: '2017 1oz Silver Athenian Owl Niue Two Dollars Elizabeth (BU)',
    category: 'one-ounce-rounds',
    price_mxn: 2450,
    images: {
      obverse: `${ASSET_BASE}/images/one-ounce-rounds/athenian_owl_obv.jpg`,
      reverse: `${ASSET_BASE}/images/one-ounce-rounds/athenian_owl_rev.jpg`,
    },
    metal: "silver",
    weight_g: 31.1035,
    stock: 7,
    inStock: true,
  },
  {
    id: '1984-1oz-silver-liberty-bell-BU',
    slug: '1984-1oz-silver-liberty-bell-BU',
    name_en: '1984 1oz Silver Liberty Bell (BU)',
    name_es: '1984 1oz Silver Liberty Bell (BU)',
    category: 'one-ounce-rounds',
    price_mxn: 2450,
    images: {
      obverse: `${ASSET_BASE}/images/one-ounce-rounds/liberty_silver_1984_obv.jpg`,
      reverse: `${ASSET_BASE}/images/one-ounce-rounds/liberty_silver_1984_rev.jpg`,
    },
    metal: "silver",
    weight_g: 31.1035,
    stock: 4,
    inStock: true,
  },
  {
    id: '2017-1oz-silver-zombucks-radioactive-BU',
    slug: '2017-1oz-silver-zombucks-radioactive-BU',
    name_en: '2017 1oz Silver Radioactive Zombucks Walker (BU)',
    name_es: '2017 1oz Silver Radioactive Zombucks Walker (BU)',
    category: 'one-ounce-rounds',
    price_mxn: 3350,
    images: {
      obverse: `${ASSET_BASE}/images/one-ounce-rounds/zombucks_obv.JPG`,
      reverse: `${ASSET_BASE}/images/one-ounce-rounds/zombucks_rev.JPG`,
    },
    metal: "silver",
    weight_g: 31.1035,
    stock: 1,
    inStock: true,
  },
  
]
