import { Product, ASSET_BASE } from "./types"

export const metadata = {
  title: 'One Troy Ounce Walking Liberty Silver Dollars US Mint 1986 to 2020'
}

export const walkingLiberty: Product[] = [
  {
    id: '1986-1oz-silver-walking-liberty-eagle-BU',
    slug: '1986-1oz-silver-walking-liberty-eagle-BU',
    name_en: '1986 1oz silver Walking Liberty and Eagle (BU)',
    name_es: '1986 1oz silver Walking Liberty and Eagle (BU)',
    category: 'walking-liberty-dollar',
    price_mxn: 6270,
    images: {
      obverse: `${ASSET_BASE}/images/walking-liberty-dollar/1986/walk_lib_1986_ms_obv.jpg`,
      reverse: `${ASSET_BASE}/images/walking-liberty-dollar/1986/walk_lib_1986_ms_rev.jpg`,
    },
    metal: "silver",
    weight_g: 31.1035,
    stock: 1,
    inStock: true,
  },
  {
    id: '1987-1oz-silver-walking-liberty-eagle-BU',
    slug: '1987-1oz-silver-walking-liberty-eagle-BU',
    name_en: '1987 1oz silver Walking Liberty and Eagle (BU)',
    name_es: '1987 1oz silver Walking Liberty and Eagle (BU)',
    category: 'walking-liberty-dollar',
    price_mxn: 5970,
    images: {
      obverse: `${ASSET_BASE}/images/walking-liberty-dollar/1987/walk_lib_1987a_ms_obv.jpg`,
      reverse: `${ASSET_BASE}/images/walking-liberty-dollar/1987/walk_lib_1987a_ms_rev.jpg`,
    },
    metal: "silver",
    weight_g: 31.1035,
    stock: 2,
    inStock: true,
  },
  {
    id: '1988-1oz-silver-walking-liberty-eagle-BU',
    slug: '1988-1oz-silver-walking-liberty-eagle-BU',
    name_en: '1988 1oz silver Walking Liberty and Eagle (BU)',
    name_es: '1988 1oz silver Walking Liberty and Eagle (BU)',
    category: 'walking-liberty-dollar',
    price_mxn: 5870,
    images: {
      obverse: `${ASSET_BASE}/images/walking-liberty-dollar/1988/walk_lib_unc_1988_01_obv.jpg`,
      reverse: `${ASSET_BASE}/images/walking-liberty-dollar/1988/walk_lib_unc_1988_01_rev.jpg`,
    },
    metal: "silver",
    weight_g: 31.1035,
    stock: 2,
    inStock: true,
  },
  {
    id: '1989-1oz-silver-walking-liberty-eagle-BU',
    slug: '1989-1oz-silver-walking-liberty-eagle-BU',
    name_en: '1989 1oz silver Walking Liberty and Eagle (BU)',
    name_es: '1989 1oz silver Walking Liberty and Eagle (BU)',
    category: 'walking-liberty-dollar',
    price_mxn: 5870,
    images: {
      obverse: `${ASSET_BASE}/images/walking-liberty-dollar/1989/walk_lib_1989_ms_obv.jpg`,
      reverse: `${ASSET_BASE}/images/walking-liberty-dollar/1989/walk_lib_1989_ms_rev.jpg`,
    },
    metal: "silver",
    weight_g: 31.1035,
    stock: 1,
    inStock: true,
  },
  {
    id: '2025-2026-15550-cosigo-token',
    slug: '2025-2026-15550-cosigo-token',
    name_en: '15,550 Cosigo Token in your wallet 2026',
    name_es: '15,550 Cosigo Token in your wallet 2026',
    category: 'walking-liberty-dollar',
    price_mxn: 950,
    images: {
      obverse: `${ASSET_BASE}/images/one-ounce-rounds/cosigo_master_256_obv.png`,
      reverse: `${ASSET_BASE}/images/one-ounce-rounds/cosigo_mark_option_x_256.png`,
    },
    metal: "silver",
    weight_g: 15.550,
    stock: 10,
    inStock: true,
  },
  {
    id: '1990-1oz-silver-walking-liberty-eagle-BU',
    slug: '1990-1oz-silver-walking-liberty-eagle-BU',
    name_en: '1990 1oz silver Walking Liberty and Eagle (BU)',
    name_es: '1990 1oz silver Walking Liberty and Eagle (BU)',
    category: 'walking-liberty-dollar',
    price_mxn: 5580,
    images: {
      obverse: `${ASSET_BASE}/images/walking-liberty-dollar/1990/walk_lib_1990_ms_obv.jpg`,
      reverse: `${ASSET_BASE}/images/walking-liberty-dollar/1990/walk_lib_1990_ms_rev.jpg`,
    },
    metal: "silver",
    weight_g: 31.1035,
    stock: 3,
    inStock: true,
  },
  {
    id: '1992-1oz-silver-walking-liberty-eagle-BU',
    slug: '1992-1oz-silver-walking-liberty-eagle-BU',
    name_en: '1992 1oz silver Walking Liberty and Eagle (BU)',
    name_es: '1992 1oz silver Walking Liberty and Eagle (BU)',
    category: 'walking-liberty-dollar',
    price_mxn: 5580,
    images: {
      obverse: `${ASSET_BASE}/images/walking-liberty-dollar/1992/walk_lib_1992a_ms_obv.jpg`,
      reverse: `${ASSET_BASE}/images/walking-liberty-dollar/1992/walk_lib_1992a_ms_rev.jpg`,
    },
    metal: "silver",
    weight_g: 31.1035,
    stock: 2,
    inStock: true,
  },
  {
    id: '1993-1oz-silver-walking-liberty-eagle-BU',
    slug: '1993-1oz-silver-walking-liberty-eagle-BU',
    name_en: '1993 1oz silver Walking Liberty and Eagle (BU)',
    name_es: '1993 1oz silver Walking Liberty and Eagle (BU)',
    category: 'walking-liberty-dollar',
    price_mxn: 5580,
    images: {
      obverse: `${ASSET_BASE}/images/walking-liberty-dollar/1993/walk_lib_1993c_ms_obv.jpg`,
      reverse: `${ASSET_BASE}/images/walking-liberty-dollar/1993/walk_lib_1993c_ms_rev.jpg`,
    },
    metal: "silver",
    weight_g: 31.1035,
    stock: 2,
    inStock: true,
  },
  {
    id: '1994-1oz-silver-walking-liberty-eagle-BU',
    slug: '1994-1oz-silver-walking-liberty-eagle-BU',
    name_en: '1994 1oz silver Walking Liberty and Eagle (BU)',
    name_es: '1994 1oz silver Walking Liberty and Eagle (BU)',
    category: 'walking-liberty-dollar',
    price_mxn: 5780,
    images: {
      obverse: `${ASSET_BASE}/images/walking-liberty-dollar/1994/walk_lib_1994a_ms_obv.jpg`,
      reverse: `${ASSET_BASE}/images/walking-liberty-dollar/1994/walk_lib_1994a_ms_rev.jpg`,
    },
    metal: "silver",
    weight_g: 31.1035,
    stock: 2,
    inStock: true,
  },
  {
    id: '1995-1oz-silver-walking-liberty-eagle-MS70',
    slug: '1995-1oz-silver-walking-liberty-eagle-MS70',
    name_en: '1995 1oz silver Walking Liberty and Eagle (MS70)',
    name_es: '1995 1oz silver Walking Liberty and Eagle (MS70)',
    category: 'walking-liberty-dollar',
    price_mxn: 6480,
    images: {
      obverse: `${ASSET_BASE}/images/sold/sold_out_trans.png`,
      reverse: `${ASSET_BASE}/images/sold/cosigo_io_infin_trans.png`,
    },
    metal: "silver",
    weight_g: 31.1035,
    stock: 0,
    inStock: true,
  },
  {
    id: '1996-1oz-silver-walking-liberty-eagle-BU',
    slug: '1996-1oz-silver-walking-liberty-eagle-BU',
    name_en: '1996 1oz silver Walking Liberty and Eagle (BU)',
    name_es: '1996 1oz silver Walking Liberty and Eagle (BU)',
    category: 'walking-liberty-dollar',
    price_mxn: 6480,
    images: {
      obverse: `${ASSET_BASE}/images/sold/sold_out_trans.png`,
      reverse: `${ASSET_BASE}/images/sold/cosigo_io_infin_trans.png`,
    },
    metal: "silver",
    weight_g: 31.1035,
    stock: 0,
    inStock: true,
  },
  {
    id: '1997-1oz-silver-walking-liberty-eagle-BU',
    slug: '1997-1oz-silver-walking-liberty-eagle-BU',
    name_en: '1997 1oz silver Walking Liberty and Eagle (BU)',
    name_es: '1997 1oz silver Walking Liberty and Eagle (BU)',
    category: 'walking-liberty-dollar',
    price_mxn: 5780,
    images: {
      obverse: `${ASSET_BASE}/images/walking-liberty-dollar/1997/walk_lib_1997_littleton_ms_obv.jpg`,
      reverse: `${ASSET_BASE}/images/walking-liberty-dollar/1997/walk_lib_1997_littleton_ms_rev.jpg`,
    },
    metal: "silver",
    weight_g: 31.1035,
    stock: 1,
    inStock: true,
  },
  {
    id: '1998-1oz-silver-walking-liberty-eagle-BU',
    slug: '1998-1oz-silver-walking-liberty-eagle-BU',
    name_en: '1998 1oz silver Walking Liberty and Eagle (BU)',
    name_es: '1998 1oz silver Walking Liberty and Eagle (BU)',
    category: 'walking-liberty-dollar',
    price_mxn: 5380,
    images: {
      obverse: `${ASSET_BASE}/images/walking-liberty-dollar/1998/walk_lib_1998_ms_obv.jpg`,
      reverse: `${ASSET_BASE}/images/walking-liberty-dollar/1998/walk_lib_1998_ms_rev.jpg`,
    },
    metal: "silver",
    weight_g: 31.1035,
    stock: 2,
    inStock: true,
  },
  {
    id: '1999-1oz-silver-walking-liberty-eagle-BU',
    slug: '1999-1oz-silver-walking-liberty-eagle-BU',
    name_en: '1999 1oz silver Walking Liberty and Eagle (BU)',
    name_es: '1999 1oz silver Walking Liberty and Eagle (BU)',
    category: 'walking-liberty-dollar',
    price_mxn: 5280,
    images: {
      obverse: `${ASSET_BASE}/images/walking-liberty-dollar/1999/walk_lib_1999a_ms_obv.jpg`,
      reverse: `${ASSET_BASE}/images/walking-liberty-dollar/1999/walk_lib_1999a_ms_rev.jpg`,
    },
    metal: "silver",
    weight_g: 31.1035,
    stock: 3,
    inStock: true,
  },
  {
    id: '1999-1oz-silver-walking-liberty-eagle-colorized-BU',
    slug: '1999-1oz-silver-walking-liberty-eagle-colorized-BU',
    name_en: '1999 1oz silver Walking Liberty and Eagle Colorized (BU)',
    name_es: '1999 1oz silver Walking Liberty and Eagle Colorized (BU)',
    category: 'walking-liberty-dollar',
    price_mxn: 5880,
    images: {
      obverse: `${ASSET_BASE}/images/walking-liberty-dollar/1999/walk_lib_1999_colorized_ms_obv.jpg`,
      reverse: `${ASSET_BASE}/images/walking-liberty-dollar/1999/walk_lib_1999_colorized_ms_obv.jpg`,
    },
    metal: "silver",
    weight_g: 31.1035,
    stock: 1,
    inStock: true,
  },
  {
    id: '2025-2026-31100-cosigo-token',
    slug: '2025-2026-31100-cosigo-token',
    name_en: '31,100 Cosigo Token in your wallet 2026',
    name_es: '31,100 Cosigo Token in your wallet 2026',
    category: 'walking-liberty-dollar',
    price_mxn: 1800,
    images: {
      obverse: `${ASSET_BASE}/images/one-ounce-rounds/cosigo_master_256_obv.png`,
      reverse: `${ASSET_BASE}/images/one-ounce-rounds/cosigo_mark_option_x_256.png`,
    },
    metal: "silver",
    weight_g: 31.1,
    stock: 10,
    inStock: true,
  },
  {
    id: '2000-1oz-silver-walking-liberty-eagle-BU',
    slug: '2000-1oz-silver-walking-liberty-eagle-BU',
    name_en: '2000 1oz silver Walking Liberty and Eagle (BU)',
    name_es: '2000 1oz silver Walking Liberty and Eagle (BU)',
    category: 'walking-liberty-dollar',
    price_mxn: 5480,
    images: {
      obverse: `${ASSET_BASE}/images/walking-liberty-dollar/2000/walk_lib_2000_ms_obv.jpg`,
      reverse: `${ASSET_BASE}/images/walking-liberty-dollar/2000/walk_lib_2000_ms_rev.jpg`,
    },
    metal: "silver",
    weight_g: 31.1035,
    stock: 2,
    inStock: true,
  },
  {
    id: '2000-1oz-silver-walking-liberty-eagle-proof-BU',
    slug: '2000-1oz-silver-walking-liberty-eagle-proof-BU',
    name_en: '2000 1oz silver Walking Liberty and Eagle Proof (BU)',
    name_es: '2000 1oz silver Walking Liberty and Eagle Proof (BU)',
    category: 'walking-liberty-dollar',
    price_mxn: 6580,
    images: {
      obverse: `${ASSET_BASE}/images/walking-liberty-dollar/2000/one_dollar_usa_walking_lib_999_silver_2000_proof_obv.jpg`,
      reverse: `${ASSET_BASE}/images/walking-liberty-dollar/2000/one_dollar_usa_walking_lib_999_silver_2000_proof_rev.jpg`,
    },
    metal: "silver",
    weight_g: 31.1035,
    stock: 1,
    inStock: true,
  },
  {
    id: '2001-1oz-silver-walking-liberty-eagle-BU',
    slug: '2001-1oz-silver-walking-liberty-eagle-BU',
    name_en: '2001 1oz silver Walking Liberty and Eagle (BU)',
    name_es: '2001 1oz silver Walking Liberty and Eagle (BU)',
    category: 'walking-liberty-dollar',
    price_mxn: 5480,
    images: {
      obverse: `${ASSET_BASE}/images/walking-liberty-dollar/2001/walk_lib_2001a_ms_obv.jpg`,
      reverse: `${ASSET_BASE}/images/walking-liberty-dollar/2001/walk_lib_2001a_ms_rev.jpg`,
    },
    metal: "silver",
    weight_g: 31.1035,
    stock: 2,
    inStock: true,
  },
  {
    id: '2001-5oz-silver-walking-liberty-eagle-colorized-BU',
    slug: '2001-5oz-silver-walking-liberty-eagle-colorized-BU',
    name_en: '2001 5oz silver set Walking Liberty and Eagle Colorized (BU)',
    name_es: '2001 5oz silver set Walking Liberty and Eagle Colorized (BU)',
    category: 'walking-liberty-dollar',
    price_mxn: 28200,
    images: {
      obverse: `${ASSET_BASE}/images/walking-liberty-dollar/2001/walk_libs_2001_all_close.jpg`,
      reverse: `${ASSET_BASE}/images/walking-liberty-dollar/2001/walk_libs_2001_cert.jpg`,
    },
    metal: "silver",
    weight_g: 155.5,
    stock: 1,
    inStock: true,
  },
  {
    id: '2002-1oz-silver-walking-liberty-eagle-BU',
    slug: '2002-1oz-silver-walking-liberty-eagle-BU',
    name_en: '2002 1oz silver Walking Liberty and Eagle (BU)',
    name_es: '2002 1oz silver Walking Liberty and Eagle (BU)',
    category: 'walking-liberty-dollar',
    price_mxn: 5280,
    images: {
      obverse: `${ASSET_BASE}/images/walking-liberty-dollar/2002/walk_lib_2002_ms_obv.jpg`,
      reverse: `${ASSET_BASE}/images/walking-liberty-dollar/2002/walk_lib_2002_ms_rev.jpg`,
    },
    metal: "silver",
    weight_g: 31.1035,
    stock: 2,
    inStock: true,
  },
  {
    id: '2002w-1oz-silver-walking-liberty-eagle-PF69',
    slug: '2002w-1oz-silver-walking-liberty-eagle-PF69',
    name_en: '2002w 1oz silver Walking Liberty and Eagle (PF69)',
    name_es: '2002w 1oz silver Walking Liberty and Eagle (PF69)',
    category: 'walking-liberty-dollar',
    price_mxn: 6280,
    images: {
      obverse: `${ASSET_BASE}/images/walking-liberty-dollar/2002/walk_lib_2002w_pf69_cameo_obv.jpg`,
      reverse: `${ASSET_BASE}/images/walking-liberty-dollar/2002/walk_lib_2002w_pf69_cameo_rev.jpg`,
    },
    metal: "silver",
    weight_g: 31.1035,
    stock: 1,
    inStock: true,
  },
  {
    id: '2003-1oz-silver-walking-liberty-eagle-BU',
    slug: '2003-1oz-silver-walking-liberty-eagle-BU',
    name_en: '2003 1oz silver Walking Liberty and Eagle (BU)',
    name_es: '2003 1oz silver Walking Liberty and Eagle (BU)',
    category: 'walking-liberty-dollar',
    price_mxn: 5280,
    images: {
      obverse: `${ASSET_BASE}/images/walking-liberty-dollar/2003/walk_lib_2003_ms_obv.jpg`,
      reverse: `${ASSET_BASE}/images/walking-liberty-dollar/2003/walk_lib_2003_ms_rev.jpg`,
    },
    metal: "silver",
    weight_g: 31.1035,
    stock: 2,
    inStock: true,
  },
  {
    id: '2004-1oz-silver-walking-liberty-eagle-BU',
    slug: '2004-1oz-silver-walking-liberty-eagle-BU',
    name_en: '2004 1oz silver Walking Liberty and Eagle (BU)',
    name_es: '2004 1oz silver Walking Liberty and Eagle (BU)',
    category: 'walking-liberty-dollar',
    price_mxn: 5480,
    images: {
      obverse: `${ASSET_BASE}/images/walking-liberty-dollar/2004/walk_lib_2004_ms_obv.jpg`,
      reverse: `${ASSET_BASE}/images/walking-liberty-dollar/2004/walk_lib_2004_ms_rev.jpg`,
    },
    metal: "silver",
    weight_g: 31.1035,
    stock: 1,
    inStock: true,
  },
  {
    id: '2005-1oz-silver-walking-liberty-eagle-BU',
    slug: '2005-1oz-silver-walking-liberty-eagle-BU',
    name_en: '2005 1oz silver Walking Liberty and Eagle (BU)',
    name_es: '2005 1oz silver Walking Liberty and Eagle (BU)',
    category: 'walking-liberty-dollar',
    price_mxn: 5280,
    images: {
      obverse: `${ASSET_BASE}/images/walking-liberty-dollar/2005/walk_lib_2005a_ms_obv.jpg`,
      reverse: `${ASSET_BASE}/images/walking-liberty-dollar/2005/walk_lib_2005a_ms_rev.jpg`,
    },
    metal: "silver",
    weight_g: 31.1035,
    stock: 2,
    inStock: true,
  },
  {
    id: '2005w-1oz-silver-walking-liberty-eagle-pf69',
    slug: '2005w-1oz-silver-walking-liberty-eagle-pf69',
    name_en: '2005w 1oz silver Walking Liberty and Eagle Proof (BU)',
    name_es: '2005w 1oz silver Walking Liberty and Eagle Proof (BU)',
    category: 'walking-liberty-dollar',
    price_mxn: 6380,
    images: {
      obverse: `${ASSET_BASE}/images/walking-liberty-dollar/2005/walk_lib_2005w_pf69_cameo_obv.jpg`,
      reverse: `${ASSET_BASE}/images/walking-liberty-dollar/2005/walk_lib_2005w_pf69_cameo_rev.jpg`,
    },
    metal: "silver",
    weight_g: 31.1035,
    stock: 1,
    inStock: true,
  },
  {
    id: '2006-1oz-silver-walking-liberty-eagle-ms69',
    slug: '2006-1oz-silver-walking-liberty-eagle-ms69',
    name_en: '2006 1oz silver Walking Liberty and Eagle (MS69)',
    name_es: '2006 1oz silver Walking Liberty and Eagle (MS69)',
    category: 'walking-liberty-dollar',
    price_mxn: 5880,
    images: {
      obverse: `${ASSET_BASE}/images/walking-liberty-dollar/2006/walk_lib_2006_slab_ms69_obv.jpg`,
      reverse: `${ASSET_BASE}/images/walking-liberty-dollar/2006/walk_lib_2006_slab_ms69_rev.jpg`,
    },
    metal: "silver",
    weight_g: 31.1035,
    stock: 1,
    inStock: true,
  },
  {
    id: '2006-1oz-silver-walking-liberty-eagle-first-strike',
    slug: '2006-1oz-silver-walking-liberty-eagle-first-strike',
    name_en: '2006 1oz silver Walking Liberty and Eagle (FS)',
    name_es: '2006 1oz silver Walking Liberty and Eagle (FS)',
    category: 'walking-liberty-dollar',
    price_mxn: 5980,
    images: {
      obverse: `${ASSET_BASE}/images/walking-liberty-dollar/2006/walk_lib_2006a_slab_ngc_gem_obv.jpg`,
      reverse: `${ASSET_BASE}/images/walking-liberty-dollar/2006/walk_lib_2006a_slab_ngc_gem_rev.jpg`,
    },
    metal: "silver",
    weight_g: 31.1035,
    stock: 1,
    inStock: true,
  },
  {
    id: '2007-1oz-silver-walking-liberty-eagle-BU',
    slug: '2007-1oz-silver-walking-liberty-eagle-BU',
    name_en: '2007 1oz silver Walking Liberty and Eagle (BU)',
    name_es: '2007 1oz silver Walking Liberty and Eagle (BU)',
    category: 'walking-liberty-dollar',
    price_mxn: 5280,
    images: {
      obverse: `${ASSET_BASE}/images/walking-liberty-dollar/2007/walk_lib_2007_slight_tone_obv.jpg`,
      reverse: `${ASSET_BASE}/images/walking-liberty-dollar/2007/walk_lib_2007_slight_tone_rev.jpg`,
    },
    metal: "silver",
    weight_g: 31.1035,
    stock: 2,
    inStock: true,
  },
  {
    id: '2008-1oz-silver-walking-liberty-eagle-BU',
    slug: '2008-1oz-silver-walking-liberty-eagle-BU',
    name_en: '2008 1oz silver Walking Liberty and Eagle (BU)',
    name_es: '2008 1oz silver Walking Liberty and Eagle (BU)',
    category: 'walking-liberty-dollar',
    price_mxn: 5080,
    images: {
      obverse: `${ASSET_BASE}/images/walking-liberty-dollar/2008/a80_obv_dollar_2008walking_99percent.jpg`,
      reverse: `${ASSET_BASE}/images/walking-liberty-dollar/2008/a80_rev_dollar_2008walking_99percent.jpg`,
    },
    metal: "silver",
    weight_g: 31.1035,
    stock: 7,
    inStock: true,
  },
  {
    id: '2009-1oz-silver-walking-liberty-eagle-BU',
    slug: '2009-1oz-silver-walking-liberty-eagle-BU',
    name_en: '2009 1oz silver Walking Liberty and Eagle (BU)',
    name_es: '2009 1oz silver Walking Liberty and Eagle (BU)',
    category: 'walking-liberty-dollar',
    price_mxn: 5280,
    images: {
      obverse: `${ASSET_BASE}/images/walking-liberty-dollar/2009/walk_lib_2009a_ms_obv.jpg`,
      reverse: `${ASSET_BASE}/images/walking-liberty-dollar/2009/walk_lib_2009a_ms_rev.jpg`,
    },
    metal: "silver",
    weight_g: 31.1035,
    stock: 2,
    inStock: true,
  },
  {
    id: '2025-2026-7770-cosigo-token',
    slug: '2025-2026-7770-cosigo-token',
    name_en: '7,770 Cosigo Token in your wallet 2026',
    name_es: '7,770 Cosigo Token in your wallet 2026',
    category: 'walking-liberty-dollar',
    price_mxn: 500,
    images: {
      obverse: `${ASSET_BASE}/images/one-ounce-rounds/cosigo_master_256_obv.png`,
      reverse: `${ASSET_BASE}/images/one-ounce-rounds/cosigo_mark_option_x_256.png`,
    },
    metal: "silver",
    weight_g: 7.77,
    stock: 10,
    inStock: true,
  },
  {
    id: "2010-2011-1oz-silver-walking-liberty-eagle-BU",
    slug: "2010-2011-1oz-silver-walking-liberty-eagle-BU",
    name_en: "2010-2011 1oz silver Walking Liberty and Eagle (BU)",
    name_es: "2010-2011 1oz silver Walking Liberty and Eagle (BU)",
    category: "walking-liberty-dollar",
    price_mxn: 2550,
    images: {
      obverse: `${ASSET_BASE}/images/sold/sold_out_trans.png`,
      reverse: `${ASSET_BASE}/images/sold/cosigo_io_infin_trans.png`,
    },
    metal: "silver",
    weight_g: 31.1035,
    stock: 0,
    inStock: true,
  },
  {
    id: '2012-1oz-silver-walking-liberty-eagle-BU',
    slug: '2012-1oz-silver-walking-liberty-eagle-BU',
    name_en: '2012 1oz silver Walking Liberty and Eagle (BU)',
    name_es: '2012 1oz silver Walking Liberty and Eagle (BU)',
    category: 'walking-liberty-dollar',
    price_mxn: 5280,
    images: {
      obverse: `${ASSET_BASE}/images/walking-liberty-dollar/2012/45853_20220201012_m.jpg`,
      reverse: `${ASSET_BASE}/images/walking-liberty-dollar/2012/45853_20220201012_m.jpg`,
    },
    metal: "silver",
    weight_g: 31.1035,
    stock: 20,
    inStock: true,
  },
  {
    id: '2013-1oz-silver-walking-liberty-eagle-BU',
    slug: '2013-1oz-silver-walking-liberty-eagle-BU',
    name_en: '2013 1oz silver Walking Liberty and Eagle (BU)',
    name_es: '2013 1oz silver Walking Liberty and Eagle (BU)',
    category: 'walking-liberty-dollar',
    price_mxn: 5380,
    images: {
      obverse: `${ASSET_BASE}/images/walking-liberty-dollar/2013/2013-silver-eagle-obverse.jpg`,
      reverse: `${ASSET_BASE}/images/walking-liberty-dollar/2013/2013-silver-eagle-reverse.jpg`,
    },
    metal: "silver",
    weight_g: 31.1035,
    stock: 5,
    inStock: true,
  },
  {
    id: '2020-1oz-silver-walking-liberty-eagle-BU',
    slug: '2020-1oz-silver-walking-liberty-eagle-BU',
    name_en: '2020 1oz silver Walking Liberty and Eagle (BU)',
    name_es: '2020 1oz silver Walking Liberty and Eagle (BU)',
    category: 'walking-liberty-dollar',
    price_mxn: 5580,
    images: {
      obverse: `${ASSET_BASE}/images/walking-liberty-dollar/2020/2020 eagle obv.jpg`,
      reverse: `${ASSET_BASE}/images/walking-liberty-dollar/2020/2020 eagle rev.jpg`,
    },
    metal: "silver",
    weight_g: 31.1035,
    stock: 4,
    inStock: true,
  },
  {
    id: "2022-1oz-silver-walking-liberty-eagle-BU'",
    slug: "2022-1oz-silver-walking-liberty-eagle-BU",
    name_en: "2022 1oz silver Walking Liberty and Eagle (BU)",
    name_es: "2022 1oz silver Walking Liberty and Eagle (BU)",
    category: "walking-liberty-dollar",
    price_mxn: 2550,
    images: {
      obverse: `${ASSET_BASE}/images/sold/sold_out_trans.png`,
      reverse: `${ASSET_BASE}/images/sold/cosigo_io_infin_trans.png`,
    },
    metal: "silver",
    weight_g: 31.1035,
    stock: 0,
    inStock: true,
  },
]


